src/Entity/Formation.php
<?php


namespace App\Entity;

use App\Repository\FormationRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Id;
use Doctrine\ORM\Mapping\ManyToOne;
use Doctrine\ORM\Mapping\ManyToMany;
use Symfony\Component\Validator\Constraints as Assert;

#[Entity(repositoryClass: FormationRepository::class)]
class Formation
{
    private const CHEMINIMAGE = "https://i.ytimg.com/vi/";

    #[Id]
    #[GeneratedValue]
    #[Column(type: "integer")]
    private ?int $id = null;

    #[Column(type: "datetime", nullable: true)]
    #[Assert\NotBlank(message: "Veuillez indiquer la date de publication")]
    private ?DateTimeInterface $publishedAt = null;

    #[Column(type: "string", length: 100, nullable: true)]
    #[Assert\NotBlank(message: "Veuillez écrire un titre")]
    private ?string $title = null;

    #[Column(type: "text", nullable: true)]
    private ?string $description = null;

    #[Column(type: "string", length: 20, nullable: true)]
    #[Assert\NotBlank(message: "Veuillez indiquer l'Id de la vidéo")]
    private ?string $videoId = null;

    #[ManyToOne(targetEntity: Playlist::class, inversedBy: "formations")]
    #[Assert\NotBlank(message: "Veuillez sélectionner une playlist")]
    private ?Playlist $playlist = null;

    #[ManyToMany(targetEntity: Categorie::class, inversedBy: "formations")]
    private Collection $categories;

    #[Column(type: "datetime", nullable: true)]
    #[Assert\NotBlank(message: "La date de création est obligatoire")]
    private ?DateTimeInterface $dateCreation = null;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }

    // Getters and setters...

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPublishedAt(): ?DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;
        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;
        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;
        return $this;
    }

    public function getVideoId(): ?string
    {
        return $this->videoId;
    }

    public function setVideoId(?string $videoId): self
    {
        $this->videoId = $videoId;
        return $this;
    }

    public function getPlaylist(): ?Playlist
    {
        return $this->playlist;
    }

    public function setPlaylist(?Playlist $playlist): self
    {
        $this->playlist = $playlist;
        return $this;
    }

    public function getDateCreation(): ?DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(?DateTimeInterface $dateCreation): self
    {
        $this->dateCreation = $dateCreation;
        return $this;
    }
    public function getPublishedAtString(): ?string
{
    if ($this->publishedAt === null) {
        return null;
    }

    return $this->publishedAt->format('Y-m-d H:i:s');
}

    public function getMiniature(): ?string
    {
        return self::CHEMINIMAGE . $this->videoId . "/default.jpg";
    }

    public function getPicture(): ?string
    {
        return self::CHEMINIMAGE . $this->videoId . "/hqdefault.jpg";
    }

    /**
     * @return Collection|Categorie[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Categorie $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Categorie $category): self
    {
        $this->categories->removeElement($category);
        return $this;
    }
}

templates/pages/accueil.html.twig
{% extends "basefront.html.twig" %}

{% block body %}
    <p class="mt-3">
        <h3>Bienvenue sur le site de MediaTek86 consacré aux formations en ligne</h3>
    </p>
    <p class="mt-3">
        Vous allez pouvoir vous former à différents outils numériques gratuitement et directement en ligne.<br />
        Dans la partie <strong><a href="{{ path('formations') }}" class="link-info">Formations</a></strong>, vous trouverez la liste des formations proposées.
        Vous pourrez faire des recherches et des tris. 
        En cliquant sur la capture, vous accèderez à la présentation plus détaillée de la formation ainsi que la vidéo correspondante.<BR />
        Vous pouvez aussi retrouver les vidéos regroupées dans des playlists, dans la partie <strong><a href="{{ path('playlists') }}" class="link-info">Playlists</a></strong>.
    </p>
    <p>
        Voici les <strong>deux dernières formations</strong> ajoutées au catalogue :
        
              <table class="table" caption="table">
            <tr>
                {% for formation in formations %}
                    <td>
                        <div class="row">
                            <div class="col">
                                <!-- emplacement photo -->
                                {% if formation.picture %}
                                    <a href="{{ path('formations.showone', {id:formation.id}) }}">
                                    <img src="{{ formation.picture }}" 
                                         class="card-img-top" style="width:100%;height:auto;" alt="image">
                                    </a>    
                                {% endif %}
                            </div>
                            <div class="col">
                                <p>{{ formation.publishedatstring }}</p>
                                <h5 class="text-info mt-1">
                                    {{ formation.title }}
                                </h5>
                                <strong>playlist : </strong>{{ formation.playlist.name }}<br />
                                <strong>catégories : </strong> 
                                {% for categorie in formation.categories %}
                                    {{ categorie.name }}&nbsp;
                                {% endfor %}
                            </div>    
                        </div>                    
                {% endfor %}    
            </tr>

        </table>        
    </p>
{% endblock %}

templates/pages/admin.categorie.html.twig
{% extends "basefront.html.twig" %}
{% block body %}

    <table class="table table-striped" caption="table">
        <thead>
           <tr>
             <div class="container">
                <div class="text-end">
                 <a href=" {{  path('logout') }}"> Se deconnecter </a>
                  </div>
              
                    <td>
                    <ul>
<form class="form-inline mt-1" method="POST" action="{{ path('admincategorieajout') }}"> 
<div class="form-group mr-1 mb-2">
    <input  type="text" class="sm" name="nom">
    <button type="submit" class="btn btn-primary mb-2 btn-sm">Ajouter une catégorie </button>
    </div>
           </td>
           </ul>
                <th class="text-center align-top" scope="col">
                    &nbsp;
                </th>

            </tr>
        </thead>
        <tbody>
            {% for categorie in categories %}
                <tr class="align-middle">
                  
               <td class="text-left">
               {% if categorie %}
                     {{ categorie.name }}
                      {% else %}
                    Pas de catégorie
                     {% endif %}
                        </td>   
                    
</td>
                    
                    <td class="text-end">
                   <a href="{{ path('admin.categorie.suppr',{id:categorie.id})}}" type="button" class="btn btn-danger" 
                    onclick="return confirm('Êtes-vous sûr de vouloir supprimer cette playlist ?');">
    Supprimer
                    </a>
                    
                     </td>
                  
                    
                  
  </td>   

              
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/pages/admin.formation.ajout.html.twig
{% extends "basefront.html.twig" %}
       
{% block body %}
 <div class="container">
                <div class="text-end">
                 <a href=" {{  path('logout') }}"> Se deconnecter </a>
                 </div>
<h2> Nouvelle Formation : </h2>
{{ form_start(formformation) }}

{{ form_end(formformation) }}




{% endblock %}

templates/pages/admin.formation.edit.html.twig
{% extends "basefront.html.twig" %}
{% block body %}
        <div class="container">
                <div class="text-end">
                 <a href=" {{  path('logout') }}"> Se deconnecter </a>
                 </div>
<h2> Formations : </h2>
{{ form_start(formformation) }}

{{ form_end(formformation) }}
{% endblock %}

templates/pages/admin.playlist.ajout.html.twig
{% extends "basefront.html.twig" %}
{% block body %}
        <div class="container">
                <div class="text-end">
                 <a href=" {{  path('logout') }}"> Se deconnecter </a>
                 </div>
<h2> Playlists : </h2>
{{ form_start(formplaylists)}}

{{ form_end(formplaylists) }}


{% endblock %}

templates/pages/admin.playlists.edit.html.twig
{% extends "basefront.html.twig" %}
{% block body %}

        <div class="container">
                <div class="text-end">
                 <a href=" {{  path('logout') }}"> Se deconnecter </a>
                 </div>
<h2> Playlists : </h2>

<div class="form-group">
    {{ form_label(formplaylists) }}


{{ form_start(formplaylists)}}

{{ form_end(formplaylists) }}

</div>

{% endblock %}

templates/pages/admin.playlists.html.twig
{% extends "basefront.html.twig" %}
  
{% block body %}
 <div class="container">
                <div class="text-end">
                 <a href=" {{  path('logout') }}"> Se deconnecter </a>
                 </div>
    <table class="table table-striped" caption="table">
        <thead>
            <tr>
                <th class="text-left align-top" scope="col">
                    playlist<br />
                    <a href="{{ path('adminplaylistssort', {champ:'name', ordre:'ASC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true"><</a>
                    <a href="{{ path('adminplaylistssort', {champ:'name', ordre:'DESC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true">></a>
                    <form class="form-inline mt-1" method="POST" action="{{ path('adminplaylists.findallcontain', {champ:'name'}) }}">
                        <div class="form-group mr-1 mb-2">
                            <input type="text" class="sm" name="recherche" 
                                   value="{% if valeur|default and not table|default %}{{ valeur }}{% endif %}">
                            <input type="hidden" name="_token" value="{{ csrf_token('filtre_name') }}">
                            <button type="submit" class="btn btn-info mb-2 btn-sm">filtrer</button>
                        </div>
                    </form>                    
                </th>
                <th class="text-left align-top" scope="col">
                    catégories
                    <form class="form-inline mt-1" method="POST" action="{{ path('adminplaylists.findallcontain', {champ:'id', table:'categories'}) }}">
                        <select class="form-select form-select-sm" name="recherche" id="recherche" onchange="this.form.submit()">
                            <option value=""></option>
                            {% for categorie in categories %}
                                <option 
                                    {% if valeur|default and valeur==categorie.id %} 
                                        selected
                                    {% endif %} 
                                    value="{{ categorie.id }}">{{ categorie.name }}
                                </option>
                            {% endfor %}
                        </select>                    
                    </form>            
                </th>
   <td>
                    <ul>
                   <a href="{{ path('adminplaylistajout')}}"type="button"  class="btn btn-primary" >Ajouter une playlist
                    </a>
                     </ul>
                    </td> 

                <th class="text-center align-top" scope="col">
                    &nbsp;
                </th>				
            </tr>
        </thead>
        <tbody>
            <!-- boucle sur les playlists -->
            {% if playlists|length > 0 %}
                {% for k in 0..playlists|length-1 %}
                    <tr class="align-middle">
                        <td>
                            <h5 class="text-info">
                                {{ playlists[k].name }}
                            </h5>
                        </td>                 
                        <td class="text-left">
                            {% set categories = playlists[k].categoriesplaylist %}
                            {% if categories|length > 0  %}
                                {% for c in 0..categories|length-1 %}
                                    &nbsp;{{ categories[c] }}                                  
                                {% endfor %}
                            {% endif %}
                        </td> 
                        <td class="text-center">
                         {% set videos = playlists[k].formations|length %}
                             {{videos}}
                              <a href="{{ path('adminplaylistssort', {champ:'length', ordre:'ASC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true"><</a>
                              <a href="{{ path('adminplaylistssort', {champ:'length', ordre:'DESC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true">></a>
                        </td>       

        
   
    <td>
                    <ul>
                   <a href="{{ path('adminplaylistsedit',{id:playlists[k].id})}}" type="button" class="btn btn-warning">Editer
                    </a>
                     </ul>
                    </td> 
                            		
                                       <td>
                    <ul>
                   <a href="{{ path('adminplaylistsuppr',{id:playlists[k].id})}}" type="button" class="btn btn-danger"onclick="return confirm('Êtes-vous sûr de vouloir supprimer cette playlist ?');">Supprimer  
                    </a>
                     </ul>
                    </td>
                    </tr>
                {% endfor %}	
            {% endif %}
        </tbody>
    </table>
{% endblock %}

templates/pages/adminformations.html.twig
{% extends "basefront.html.twig" %}
       
{% block body %}
 <div class="container">
                <div class="text-end">
                 <a href=" {{  path('logout') }}"> Se deconnecter </a>
                 </div>
    <table class="table table-striped" caption="table">
        <thead>
            <tr>
                <th class="text-left align-top" scope="col">
                    formation<br />
                        <a href="{{ path('adminformationssort', {'champ': 'title', 'ordre': 'ASC' }) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true">&lt;</a>
                      <a href="{{ path('adminformationssort', {'champ': 'title', 'ordre': 'DESC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true">&gt;</a>
                       <form class="form-inline mt-1" method="POST" action="{{ path('adminformations.findallcontain', {champ:'title'}) }}">
                        <div class="form-group mr-1 mb-2">
                            <input type="text" class="sm" name="recherche" 
                                   value="{% if valeur|default and not table|default %}{{ valeur }}{% endif %}">
                            <input type="hidden" name="_token" value="{{ csrf_token('filtre_title') }}">
                            <button type="submit" class="btn btn-info mb-2 btn-sm">filtrer</button>
                        </div>
                    </form         
                </th>
                <th class="text-left align-top" scope="col">
                    playlist<br />
                    <a href="{{ path('adminformationssort', {table:'playlist', champ:'name', ordre:'ASC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true"><</a>
                    <a href="{{ path('adminformationssort', {table:'playlist', champ:'name', ordre:'DESC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true">></a>
                    <form class="form-inline mt-1" method="POST" action="{{ path('adminformations.findallcontain', {champ:'name', table:'playlist'}) }}">
                        <div class="form-group mr-1 mb-2">
                            <input type="text" class="sm" name="recherche" 
                                   value="{% if valeur|default and table|default and table=='playlist' %}{{ valeur }}{% endif %}">
                            <input type="hidden" name="_token" value="{{ csrf_token('filtre_name') }}">
                            <button type="submit" class="btn btn-info mb-2 btn-sm">filtrer</button>
                        </div>
                    </form>                    
                </th>
                <th class="text-left align-top" scope="col">
                    catégories
                    <form class="form-inline mt-1" method="POST" action="{{ path('adminformations.findallcontain', {champ:'id', table:'categories'}) }}">
                        <select class="form-select form-select-sm" name="recherche" id="recherche" onchange="this.form.submit()">
                            <option value=""></option>
                            {% for categorie in categories %}
                                <option 
                                    {% if valeur|default and valeur==categorie.id %} 
                                        selected
                                    {% endif %} 
                                    value="{{ categorie.id }}">{{ categorie.name }}
                                </option>
                            {% endfor %}
                        </select>                    
                    </form>            
                </th>
                <th class="text-center align-top" scope="col">
                    date<br />
                    <a href="{{ path('adminformationssort', {champ:'publishedAt', ordre:'ASC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true"><</a>
                    <a href="{{ path('adminformationssort', {champ:'publishedAt', ordre:'DESC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true">></a>                    

                </th>
                    <td>
                    <ul>
                   <a href="{{ path('adminformationajout')}}"type="button"  id="button"class="btn btn-primary" >Ajouter une formation
                    </a>
                     </ul>
                    </td> 
                <th class="text-center align-top" scope="col">
                    &nbsp;
                </th>

            </tr>
        </thead>
        <tbody>
            {% for formation in formations %}
                <tr class="align-middle">
                    <td>
                        <h5 class="text-info">
                            {{ formation.title }}
                        </h5>
                    </td>
               <td class="text-left">
               {% if formation.playlist %}
                     {{ formation.playlist.name }}
                      {% else %}
                    Pas de playlist
                     {% endif %}
                </td>                
                    <td class="text-left">
                        {% for categorie in formation.categories %}
                            {{ categorie.name }}<br />
                        {% endfor %}
                    </td> 

                 
    <td>
                    <ul>
                   <a href="{{ path('admin.formation.edit',{id:formation.id})}}" type="button" class="btn btn-warning">Editer
                    </a>
                     </ul>
                    </td> 
   <td>
                    <ul>
                   <a href="{{ path('admin.formations.suppr',{id:formation.id})}}" type="button" class="btn btn-danger" 
                    onclick="return confirm('Êtes-vous sûr de vouloir supprimer cette playlist ?');">
    Supprimer
                    </a>
                     </ul>
                    </td>


                    <td class="text-center">
                        {{ formation.publishedatstring }}
                    </td>
                    <td class="text-center">
                        {% if formation.miniature %}
                            <a href="{{ path('formations.showone', {id:formation.id}) }}">
                                <img src="{{ formation.miniature }}" alt="formation miniature">
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/pages/formation.html.twig
{% extends "basefront.html.twig" %}
{% block body %}
    <div class="row mt-3">
        <div class="col">
            <!-- emplacement de la vidéo -->
            {% if formation.videoid %}
                <div style="width: 560px; height: 315px; float: none; clear: both; margin: 2px auto;">
                  <embed
                    src="https://www.youtube.com/embed/{{ formation.videoid }}" 
                    wmode="transparent"
                    type="video/mp4"
                    width="100%" height="100%"
                    allow="autoplay; clipboard-write; encrypted-media; picture-in-picture"
                    allowfullscreen
                    title="YouTube video player"
                  >
                </div>                                             
            {% endif %}
        </div>
        <div class="col">
            {{ formation.publishedatstring }}
            <h4 class="text-info mt-5">{{ formation.title }}</h4>
            <strong>playlist : </strong>{{ formation.playlist.name }}<br />
            <strong>catégories : </strong>
                {% for categorie in formation.categories %}
                    {{ categorie.name }}&nbsp;
                {% endfor %}
            <br /><br />
            <strong>description :</strong><br />
                {{ formation.description|nl2br }}
        </div>
    </div>
{% endblock %}

templates/pages/formations.html.twig
{% extends "basefront.html.twig" %}
{% block body %}

    <table class="table table-striped" caption="table">
        <thead>
            <tr>
                <th class="text-left align-top" scope="col">
                    formation<br />
                    <a href="{{ path('formations.sort', {champ:'title', ordre:'ASC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true"><</a>
                    <a href="{{ path('formations.sort', {champ:'title', ordre:'DESC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true">></a>
                    <form class="form-inline mt-1" method="POST" action="{{ path('formations.findallcontain', {champ:'title'}) }}">
                        <div class="form-group mr-1 mb-2">
                            <input type="text" class="sm" name="recherche" 
                                   value="{% if valeur|default and not table|default %}{{ valeur }}{% endif %}">
                            <input type="hidden" name="_token" value="{{ csrf_token('filtre_title') }}">
                            <button type="submit" class="btn btn-info mb-2 btn-sm">filtrer</button>
                        </div>
                    </form>                    
                </th>
                <th class="text-left align-top" scope="col">
                    playlist<br />
                    <a href="{{ path('formations.sort', {table:'playlist', champ:'name', ordre:'ASC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true"><</a>
                    <a href="{{ path('formations.sort', {table:'playlist', champ:'name', ordre:'DESC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true">></a>
                    <form class="form-inline mt-1" method="POST" action="{{ path('formations.findallcontain', {champ:'name', table:'playlist'}) }}">
                        <div class="form-group mr-1 mb-2">
                            <input type="text" class="sm" name="recherche" 
                                   value="{% if valeur|default and table|default and table=='playlist' %}{{ valeur }}{% endif %}">
                            <input type="hidden" name="_token" value="{{ csrf_token('filtre_name') }}">
                            <button type="submit" class="btn btn-info mb-2 btn-sm">filtrer</button>
                        </div>
                    </form>                    
                </th>
                <th class="text-left align-top" scope="col">
                    catégories
                    <form class="form-inline mt-1" method="POST" action="{{ path('formations.findallcontain', {champ:'id', table:'categories'}) }}">
                        <select class="form-select form-select-sm" name="recherche" id="recherche" onchange="this.form.submit()">
                            <option value=""></option>
                            {% for categorie in categories %}
                                <option 
                                    {% if valeur|default and valeur==categorie.id %} 
                                        selected
                                    {% endif %} 
                                    value="{{ categorie.id }}">{{ categorie.name }}
                                </option>
                            {% endfor %}
                        </select>                    
                    </form>            
                </th>
                <th class="text-center align-top" scope="col">
                    date<br />
                    <a href="{{ path('formations.sort', {champ:'publishedAt', ordre:'ASC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true"><</a>
                    <a href="{{ path('formations.sort', {champ:'publishedAt', ordre:'DESC'}) }}" class="btn btn-info btn-sm active" role="button" aria-pressed="true">></a>                    
                </th>
                <th class="text-center align-top" scope="col">
                    &nbsp;
                </th>
            </tr>
        </thead>
        <tbody>
            {% for formation in formations %}
                <tr class="align-middle">
                    <td>
                        <h5 class="text-info">
                            {{ formation.title }}
                        </h5>
                    </td>
                    <td class="text-left">
                        {{ formation.playlist.name }}                  
                    </td>                    
                    <td class="text-left">
                        {% for categorie in formation.categories %}
                            {{ categorie.name }}<br />
                        {% endfor %}
                    </td>                    
                    <td class="text-center">
                        {{ formation.publishedatstring }}
                    </td>
                    <td class="text-center">
                        {% if formation.miniature %}
                            <a href="{{ path('formations.showone', {id:formation.id}) }}">
                                <img src="{{ formation.miniature }}" alt="formation miniature">
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
   
{% endblock %}

templates/pages/playlist.html.twig
{% extends "basefront.html.twig" %}
{% block body %}
    <div class="row mt-3">
        <div class="col">
            <h4 class="text-info mt-5">{{ playlist.name }}</h4>
            <strong>catégories : </strong>
                <!-- boucle pour afficher les catégories -->
                {% set anccategorie = '' %}
                {% for playlist in playlistcategories %}
                    {{ playlist.name }}&nbsp;
                {% endfor %}
            <br /><br />
             {% set videos = playlist.formations|length %} <strong> {{videos}} <p> vidéos </p> </strong>
          <strong>description :</strong><br />
                {{ playlist.description|nl2br }}
          
            
        </div>
        <div class="col">
            <!-- boucle sur l'affichage des formations -->
            {% for formation in playlistformations %}
                <div class="row mt-1">
                    <div class="col-md-auto">
                        {% if formation.miniature %}
                            <a href="{{ path('formations.showone', {id:formation.id}) }}">
                                <img src="{{ formation.miniature }}" alt="formation miniature">
                            </a>
                        {% endif %}  
                    </div>
                    <div class="col d-flex align-items-center">
                        <a href="{{ path('formations.showone', {id:formation.id}) }}" 
                           class="link-secondary text-decoration-none">
                            {{ formation.title }}
                        </a>          
                    </div>
                </div>
            {% endfor %}
        </div>
        
    </div>
{% endblock %}